package com.kp.borju_kp.utils

import android.content.Context
import android.os.Environment
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.TextAlignment
import com.kp.borju_kp.data.Pengeluaran
import java.io.File
import java.text.SimpleDateFormat
import java.util.Locale

object PdfExporter {

    fun createPengeluaranPdf(context: Context, data: List<Pengeluaran>, title: String): File {
        // Buat nama file unik
        val timeStamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(System.currentTimeMillis())
        val pdfFileName = "Laporan_Pengeluaran_$timeStamp.pdf"

        // Tentukan lokasi penyimpanan (Folder Downloads)
        val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
        val pdfFile = File(downloadsDir, pdfFileName)

        // Mulai proses pembuatan PDF
        val writer = PdfWriter(pdfFile)
        val pdfDoc = PdfDocument(writer)
        val document = Document(pdfDoc)

        // Tambahkan Judul
        document.add(Paragraph(title).setBold().setFontSize(18f).setTextAlignment(TextAlignment.CENTER))
        document.add(Paragraph("Generated by BORJU App").setTextAlignment(TextAlignment.CENTER))
        document.add(Paragraph("\n")) // Spasi

        // Buat Tabel
        val table = Table(floatArrayOf(1f, 4f, 2f, 3f)) // Lebar kolom
        table.setWidth(100f)

        // Header Tabel
        table.addHeaderCell("No.")
        table.addHeaderCell("Nama Pengeluaran")
        table.addHeaderCell("Kategori")
        table.addHeaderCell("Jumlah")

        var totalPengeluaran = 0.0
        // Isi Tabel dengan Data
        data.forEachIndexed { index, pengeluaran ->
            table.addCell((index + 1).toString())
            table.addCell(pengeluaran.namaPengeluaran)
            table.addCell(pengeluaran.kategori)
            table.addCell("Rp ${String.format("%,.0f", pengeluaran.jumlah)}")
            totalPengeluaran += pengeluaran.jumlah
        }

        document.add(table)
        document.add(Paragraph("\n")) // Spasi

        // Tambahkan Total
        document.add(Paragraph("Total Pengeluaran: Rp ${String.format("%,.0f", totalPengeluaran)}").setBold().setTextAlignment(TextAlignment.RIGHT))

        // Tutup dokumen
        document.close()

        return pdfFile
    }
}